name: NPM Publish
on:
  workflow_dispatch:
  push:
    branches: [master]

permissions: write-all

concurrency: babel-plugin-publish

jobs:
  publish:
    # don't run on lerna publish commits
    if: ${{ ! contains(github.event.head_commit.message, 'chore(lerna)') }}
    uses: audioeye/github-actions/.github/workflows/publish-packages.yml@main
    secrets: inherit
